development:
  adapter: postgresql
  #url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: postgresql
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: metadata_management_production
